blank_issues_enabled: false
contact_links:
  - name: Security vulnerability
    url: https://github.com/bishaldahal/M3U8-HLS-Player-with-Custom-Controls/security/advisories/new
    about: Please report security issues privately.
  - name: Questions & discussion
    url: https://github.com/bishaldahal/M3U8-HLS-Player-with-Custom-Controls/discussions
    about: Ask questions and share ideas.
