name: Upload to Edge store

on:
  push:
    branches:
    - master
    tags:
      - '*release*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm ci

    - name: Build and minify
      run: npm run release:minify

    - name: Publish to Edge store
      run: npm run publish
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        PRODUCT_ID: ${{ secrets.PRODUCT_ID }}
        ACCESS_TOKEN_URL: ${{ secrets.ACCESS_TOKEN_URL }}